name: codeforb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.4.1
  google_fonts: ^6.2.1
  image_picker: ^1.0.7 # For camera access
  fl_chart: ^0.67.0   # For beautiful charts
  percent_indicator: ^4.2.3 # For progress bars
  image_picker_for_web: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 
flutter:
  uses-material-design: true